filter_secrets: false
language: node_js
node_js: stable
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
env:
  global:
  - GOOGLE_APPLICATION_CREDENTIALS="${PWD}/client-secret.json"
  - PROJECT_NAME_STG=K8s-Demo
  - CLUSTER_NAME_STG=flux-baremetal-cluster
  - CLOUDSDK_COMPUTE_ZONE=us-central1-a
  - DOCKER_IMAGE_NAME=avneetsingh/travis
  - KUBE_DEPLOYMENT_NAME=openebs
  - KUBE_DEPLOYMENT_CONTAINER_NAME=openebs
  - PATH=$PATH:${HOME}/google-cloud-sdk/bin
dist: trusty
sudo: false
services:
- docker
before_script:
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud --quiet version
- gcloud --quiet components update
script:
- gcloud components update kubectl
- gcloud auth activate-service-account --key-file "${GOOGLE_APPLICATION_CREDENTIALS}"
- kubectl apply -f config/stage-openebs.yaml
notifications:
  email: "-atul.abhishek@openebs.io"
before_install:
- openssl aes-256-cbc -K $encrypted_1c66bdd57eb0_key -iv $encrypted_1c66bdd57eb0_iv
  -in client-secret.json.enc -out client-secret.json -d
