language: node_js
node_js: stable
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::6}
before_install:
  - stty cols 80
  - openssl aes-256-cbc -K $encrypted_1c66bdd57eb0_key -iv $encrypted_1c66bdd57eb0_iv
    -in client-secret.json.enc -out client-secret.json -d
dist: trusty
sudo: required
services:
  - docker
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable fluxbox
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- fluxbox >/dev/null 2>&1 &
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then export REPO=avneetsingh/openebs-website;
        cd openebs_pro;
        docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" && docker build -t $REPO:$COMMIT . && docker push $REPO; 
    fi
  - cd ..
  - ./deploy
  - ./trigger-dependent-build
notifications:
  email:

